name: SimpleExample

on: [push]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@v4
    # Build
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - run: python my_script.py
# This is a simple workflow for a python app